#pragma once

#define FVM_DATA_STACK_LENGTH 1024
#define FVM_DICTIONARY_LENGTH 16384
#define FVM_CONDITIONS_STACK_LENGTH 32
#define FVM_WORD_NAME_LENGTH 32

#ifndef NULL
#define NULL 0
#endif

#define CPU_BITS 32
//#define FVM_FP_ENABLE